### ISSUE TITLE
Improve MP_ADDADDR text

### ISSUE THREAD

**Issue by markusa** [tsvwg/ietf-multipath-dccp#242]
Olivier's comment in https://mailarchive.ietf.org/arch/msg/tsvwg/T-9P8iVoU5i89VK9QJXnOG_IsL4/

```
For MP_ADDADDR, you might explain that each host maintains a list of 
unique address identifiers and that it manages them as it wishes.
```

**Comment by veselinrak** [comment]
Sentence 'Each host maintains a list of unique address identifiers and manages these as it wishes.' added to 3.2.8 MP_ADDADDR section.
