### ISSUE TITLE
Improve Maximum Packet Size Considerations text

### ISSUE THREAD

**Issue by markusa** [tsvwg/ietf-multipath-dccp#249]
Olivier's comment in https://mailarchive.ietf.org/arch/msg/tsvwg/T-9P8iVoU5i89VK9QJXnOG_IsL4/

```
If MPDCCP uses the minimum MPS accross all paths, there is a risk that 
an on-path attack on one path forces the utilization of very small 
packets on all paths. MPDCCP should be able to detect this attack and 
drop paths with a too low MPS
```

**Comment by gorryfair** [comment]
I suggest the security considerations could say something like:
If MPDCCP uses a minimum MPS across all paths, 
any change to one path impacts the sender for all paths.
To mitigate attacks that seek to force a low MPS, MPDCCP 
could detect an attempt to reduce the MPS less than a minimum MPS, and then 
stop using these paths.
