### ISSUE TITLE
move repo to tsvwg GitHub org

### ISSUE THREAD

**Issue by marten-seemann** [tsvwg/ietf-multipath-dccp#253]
As discussed at IETF 117, we'd like to move all adopted WG drafts to the [TSVWG GitHub org](https://github.com/tsvwg).

The easiest way to do so would be by adding me as an Admin of this repo (in Settings -> Collaboration and teams, then click Add People), since GitHub requires one to be admin of the repo that's being moved and of the organization this repo is being moved to. Transferring a repo preserves all Git history, GitHub issues, PRs, etc. It also adds an HTTP forwarding from the old URL to the new See https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository for more details.

**Comment by markusa** [comment]
Hi Marten,

1. Will we stay admin of the repo also under the new TSVWG organization?
2. Does the workflow of the Github actions to create the draft remain the same?

**Comment by marten-seemann** [comment]
Thanks for the invite. I looks like I have admin permissions though (only collaborator?), so I won't be able to transfer the repo. Can you please check?

**Comment by markusa** [comment]
There is no setting I can change. Under Settings I only have the entry "Collaborators" available without "and teams". Also, there is no way to change the " Collaborator" role to another one. From what I read, the admin role is dedicated to organizations?!

However, I can start the process of transferring the repository under Settings ->General. So probably it is the other way round and you have to give me the right in TSVWG org to create repos, see:

**Transfer repository: markusa/ietf-multipath-dccp**
Transfer this repository to another user or to an organization where you have the ability to create repositories.

**Comment by marten-seemann** [comment]
Interesting. Sorry, still figuring out the best process here :)

I just added you as a member in TSVWG. Can you try transferring the repo please?

**Comment by markusa** [comment]
Done. I close this issue now.
