### ISSUE TITLE
Please do not squat on IANA Registries - revert or request early assignment

### ISSUE THREAD

**Issue by gorryfair** [tsvwg/ietf-multipath-dccp#257]
This ID contains a number of requests to IANA for assignments.

An ID cannot proceed with enumerated values in advance of an official IANA assignment. This is known as "squatting", i.e. using prior to allocation.

Please consider (a) Reverting to use a logical value THIS-XXX throughout, 
or (b) making a formal request for Early Allocation to the WG Chair which includes the IANA text here, asking IANA for a provisional assignment in the registry. Early allocation requests must be submitted by the relevant IETF WG chair. Any early allocations are marked as TEMPORARY in the registry and must be reviewed annually. 

Given the maturity of the Spec, approach (b) would seem reasonable, please discuss with the WG Chair if the editors would like to do this.

**Comment by markusa** [comment]
We ask the WG chair for option b)
