### ISSUE TITLE
Expired drafts in references

### ISSUE THREAD

**Issue by zaheduzzaman** [tsvwg/ietf-multipath-dccp#297]
https://github.com/tsvwg/ietf-multipath-dccp/blob/b8cc70de1761ddf446f1782fd8b0c728ac032a5d/draft-ietf-tsvwg-multipath-dccp.mkd?plain=1#L200-L206

This paragraph references expired drafts and external materials. While these might provide some interesting background information, as per my information there are no plans to progress those expired documents, hence, I would suggest to remove them and provide summery of the contents in this specification (as per of the introduction section or in the appendix). 

I think the ATSSS reference is good one to keep but then provide more text than just reference to the 3GPP TS. It is also perhaps OK to keep the references to the IETF slides and paper published on DCCP for further details.

**Comment by markusa** [comment]
Changed in #307
