### ISSUE TITLE
Unclear intention with DCCP framework and header conversion 

### ISSUE THREAD

**Issue by zaheduzzaman** [tsvwg/ietf-multipath-dccp#298]
https://github.com/tsvwg/ietf-multipath-dccp/blob/b8cc70de1761ddf446f1782fd8b0c728ac032a5d/draft-ietf-tsvwg-multipath-dccp.mkd?plain=1#L208-L209

I am not sure about the intention with the referenced draft. are those necessary to understand this specification and or deploy this specification? Without clear intention, the can just create more questions. 

We can simple state encapsulation is out of scope of the PS specification, without further details on unclear goal/unfinished work.

**Comment by markusa** [comment]
Changed in https://github.com/tsvwg/ietf-multipath-dccp/pull/307
