### ISSUE TITLE
MP-QUIC??

### ISSUE THREAD

**Issue by zaheduzzaman** [tsvwg/ietf-multipath-dccp#299]
https://github.com/tsvwg/ietf-multipath-dccp/blob/b8cc70de1761ddf446f1782fd8b0c728ac032a5d/draft-ietf-tsvwg-multipath-dccp.mkd?plain=1#L211-L214

Could you please explain why MP-DCCP specification need to talk about MP-QUIC? I suggest we remove this.

**Comment by markusa** [comment]
We had two reviewer comments from Med and Olivier requesting a comparison with MP-QUIC. I personally agree with removing the MP-QUIC reference in this paragraph. I have opened a PR.
