### ISSUE TITLE
confusion about tunneling or encapsulation of lower layeres 

### ISSUE THREAD

**Issue by zaheduzzaman** [tsvwg/ietf-multipath-dccp#300]
If encapsulation of UDP,IP is not in the scope of this specification then how do I interpret the following statements ?

https://github.com/tsvwg/ietf-multipath-dccp/blob/b8cc70de1761ddf446f1782fd8b0c728ac032a5d/draft-ietf-tsvwg-multipath-dccp.mkd?plain=1#L219-L220

**Comment by markusa** [comment]
Sentence removed in PR #309
