### ISSUE TITLE
Editorial suggestion - move the subflow definition up

### ISSUE THREAD

**Issue by zaheduzzaman** [tsvwg/ietf-multipath-dccp#301]
https://github.com/tsvwg/ietf-multipath-dccp/blob/b8cc70de1761ddf446f1782fd8b0c728ac032a5d/draft-ietf-tsvwg-multipath-dccp.mkd?plain=1#L259-L260

I think it would be better to define subflow before defining DCCP connection using subflow.

**Comment by markusa** [comment]
Changed in #310
