### ISSUE TITLE
What does "physically isolated path" mean?

### ISSUE THREAD

**Issue by zaheduzzaman** [tsvwg/ietf-multipath-dccp#302]
https://github.com/tsvwg/ietf-multipath-dccp/blob/b8cc70de1761ddf446f1782fd8b0c728ac032a5d/draft-ietf-tsvwg-multipath-dccp.mkd?plain=1#L290

Please explain - "physically isolated path"? is this something different than paths are defined using 4 tuples?

**Comment by gorryfair** [comment]
- was this a different set of links/routers ?

**Comment by markusa** [comment]
Reformulated in #311
