### ISSUE TITLE
How one should interpret the all capitalized "ALL"?

### ISSUE THREAD

**Issue by zaheduzzaman** [tsvwg/ietf-multipath-dccp#304]
https://github.com/tsvwg/ietf-multipath-dccp/blob/b8cc70de1761ddf446f1782fd8b0c728ac032a5d/draft-ietf-tsvwg-multipath-dccp.mkd?plain=1#L314

Where is the interpretation of "ALL" defined, not in RFC 2119 I guess?

**Comment by markusa** [comment]
@zaheduzzaman, the “All” is not capitalized, except for the first character at the beginning of the sentence.

**Comment by zaheduzzaman** [comment]
I might have misread it.
