### ISSUE TITLE
MP_MAXNUM_SUBFLOW

### ISSUE THREAD

**Issue by zaheduzzaman** [tsvwg/ietf-multipath-dccp#306]
I understand we can create infinite number of subflows in a MP-DCCP connection and there is a recommendation limit the number of subflows. However, would it not be better to define a MP feature MP_MAXNUM_SUBFLOW to exchange the imposed limit to the peers,so that it is much clearner to put restrictions via signaling on the connection and save the client from trying to creat new subflows and server from rejecting it?

If this dicusison has already happend please point me the conclusion(s).

**Comment by markusa** [comment]
In all previous implementations, this was not a required feature. MPTCP also defines neither a limit nor a signaling of limits.

However, I could imagine specifying this as an extension should it be required in the future.

**Comment by zaheduzzaman** [comment]
That is one way of dealing with this. However, this would then require warrant/consideration on limiting the number of subflows. If I am not mistaken the current specification does not do that either.
